---
- name: httpd install
  hosts: all
  tasks:
   - name: httpd install
     yum:
      name: httpd
      state: latest
   - name: download the httpd.conf
     get_url:
      url: https://pepa.holla.cz/wp-content/uploads/2016/12/Ansible.pdf
      dest: /var/www/html/ansible.pdf
      mode: 0644
     notify:
      - restart httpd
  handlers:
   - name: restart httpd
     service:
      name: httpd
      state: restarted
      enabled: yes