- name: httpd install
  hosts: all
  tasks:
   - name: httpd install
     yum:
      name: httpd
      state: latest
     tags:
       - httpd
   - name: download the httpd.conf
     get_url:
      url: https://www.comp.nus.edu.sg/~seer/book/2e/Ch01.%20Cloud%20Computing.pdf
      dest: /var/www/html/ansible.pdf
      mode: 0644
     notify:
      - restart httpd
     tags:
       - httpd
   - name: install vsftpd
     yum:
      name: vsftpd
      state: latest
     tags:
       -  vsftpd
   - name: start the service
     service:
      name: vsftpd
      state: started
     tags:
       - vsftpd
  handlers:
   - name: restart httpd
     service:
      name: httpd
      state: restarted
      enabled: yes
